lst=[1,23,'Dipu',34]
print(lst)
lst.append('DDDD')
print(lst)
lst.remove('DDDD')
print(lst)
lst.insert(2,900)
print(lst)
lst.reverse()
print(lst)
lst.pop()
print(lst)
lst2=['Hi',5]
lst.extend(lst2)
print(lst)

country=['Bangladesh','Germany','Switzerland']
country.append('Russia')
country.pop(1)
country.insert(int(len(country)/2),'USA')
print(country)